services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wa-chatbot-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - wa-chatbot-network

  web:
    image: nginx:1.27-alpine
    container_name: wa-chatbot-web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - wa-chatbot-network

networks:
  wa-chatbot-network:
    driver: bridge
